global:
  scrape_interval: 15s 
  evaluation_interval: 15s  

scrape_configs:

  - job_name: 'dotnet_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5006']


  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
