# Workflow para build, testes unitários e verificação de segurança do projeto LocalFriendz.
# Este workflow é acionado em pushs e pull requests na branch 'master'.

name: CI Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  ConnectionStrings__PostgreSqlConnection: "Host=localhost;Database=DB_FIAP_ARQUITETO;Username=postgres;Password=Teste@123"
  ASPNETCORE_URLS: http://+:5006
  ASPNETCORE_ENVIRONMENT: Development

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Faz o checkout do repositório para acessar o código fonte
      - name: Step 1 Checkout Repository
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente .NET com a versão especificada
      - name: Step 2 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Passo 3: Restaura dependências necessárias para o projeto LocalFriendz
      - name: Restore dependencies for main project
        run: dotnet restore ./LocalFriendzApi/src/LocalFriendzApi/LocalFriendzApi.csproj

      - name: Build main project
        run: dotnet build ./LocalFriendzApi/src/LocalFriendzApi/LocalFriendzApi.csproj --configuration Release --no-restore

  validation_security:
    runs-on: ubuntu-latest
    needs: build
    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy Security Scan
        run: trivy fs --exit-code 0 --no-progress --severity MEDIUM,HIGH,CRITICAL .

      - name: Restore dependencies
        run: dotnet restore ./LocalFriendzApi/src/LocalFriendzApi/LocalFriendzApi.csproj

      - name: Run dotnet security check
        run: dotnet list ./LocalFriendzApi/src/LocalFriendzApi/LocalFriendzApi.csproj package --vulnerable



  tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Teste@123
          POSTGRES_DB: DB_FIAP_ARQUITETO
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --network-alias db
    steps:
      # Passo 1: Checkout do repositório para acessar o código fonte
      - name: Step 1 Checkout Repository
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente .NET com a versão especificada
      - name: Step 2 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: list docker containers
        run: docker container ls

      - name: Run SQL Script to Create Database and Tables
        run: |
          PGPASSWORD=Teste@123 psql -h localhost -U postgres -d DB_FIAP_ARQUITETO -f ./LocalFriendzApi/scripts/FiapDB.sql

      - name: Restore dependencies for test project
        run: dotnet restore ./LocalFriendzApi/src/LocalFriendzApi.Test/LocalFriendzApi.IntegrationTests.csproj

      - name: Build Test Project
        run: dotnet build ./LocalFriendzApi/src/LocalFriendzApi.Test/LocalFriendzApi.IntegrationTests.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./LocalFriendzApi/src/LocalFriendzApi.Test/LocalFriendzApi.IntegrationTests.csproj --configuration Release --no-build --verbosity detailed
